from datetime import date, datetime, timedelta
from typing import List
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc, func

from database import get_db
from models.domain import DailyTask, CoinLedger, User, BloodReport
from security.jwt_handler import get_current_user_id

router = APIRouter(prefix="/api/tasks", tags=["Tasks"])

@router.get("/today")
async def get_today_tasks(
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Get today's tasks generated by the analysis engine."""
    today = date.today()
    result = await db.execute(
        select(DailyTask)
        .where(DailyTask.user_id == user_id, DailyTask.task_date == today)
        .order_by(DailyTask.time_of_day)
    )
    tasks = result.scalars().all()
    
    # Serialize to dicts for JSON response
    return [
        {
            "id": str(t.id),
            "task_type": t.task_type,
            "task_name": t.task_name,
            "description": t.description,
            "why_this_task": t.why_this_task,
            "category": t.category,
            "time_of_day": t.time_of_day,
            "time_slot": t.time_of_day,  # Alias for Missions screen
            "duration_or_quantity": t.duration_or_quantity,
            "coins_reward": t.coins_reward,
            "completed": t.completed,
            "completed_at": str(t.completed_at) if t.completed_at else None,
        }
        for t in tasks
    ]

@router.post("/{task_id}/complete")
async def complete_task(
    task_id: str,
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Mark task as complete and award coins."""
    result = await db.execute(
        select(DailyTask).where(DailyTask.id == task_id, DailyTask.user_id == user_id)
    )
    task = result.scalar_one_or_none()
    
    if not task:
        raise HTTPException(status_code=404, detail="Task not found.")
    if task.completed:
        return {"message": "Task already completed", "coins_awarded": 0}

    # 1. Mark Complete
    task.completed = True
    task.completed_at = datetime.utcnow()

    # 2. Award Coins
    reward = CoinLedger(
        user_id=user_id,
        amount=task.coins_reward,
        activity_type=f"TASK_COMPLETION_{task.task_type}"
    )
    db.add(reward)
    
    await db.flush()
    
    # 3. Get new balance
    balance_res = await db.execute(
        select(func.sum(CoinLedger.amount)).where(CoinLedger.user_id == user_id)
    )
    new_balance = balance_res.scalar() or 0
    await db.commit()

    return {
        "message": "Task completed successfully",
        "coins_awarded": task.coins_reward,
        "new_balance": new_balance
    }

@router.get("/history")
async def get_task_history(
    limit: int = Query(50, ge=1, le=100),
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Get history of completed tasks."""
    result = await db.execute(
        select(DailyTask)
        .where(DailyTask.user_id == user_id, DailyTask.completed == True)
        .order_by(desc(DailyTask.completed_at))
        .limit(limit)
    )
    return result.scalars().all()

@router.get("/balance")
async def get_coin_balance(
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Calculate current coin balance."""
    result = await db.execute(
        select(func.sum(CoinLedger.amount)).where(CoinLedger.user_id == user_id)
    )
    balance = result.scalar() or 0
    return {"balance": balance}

@router.get("/monthly-status")
async def get_monthly_task_status(
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """
    Returns the monthly report upload task status.
    - eligible: True if 30+ days since last report (can earn 50 coins)
    - days_since_last: how many days since last report
    - coins_awarded_this_month: whether coins already given this month
    """
    # Get last two reports ordered by date
    result = await db.execute(
        select(BloodReport)
        .where(BloodReport.user_id == user_id)
        .order_by(desc(BloodReport.uploaded_at))
        .limit(2)
    )
    reports = result.scalars().all()

    if not reports:
        return {
            "eligible": False,
            "days_since_last": None,
            "message": "Upload your first blood report to start tracking.",
            "coins_reward": 50,
        }

    last_report = reports[0]
    days_since = (datetime.utcnow() - last_report.uploaded_at).days

    # Check if monthly coins already awarded this calendar month
    month_start = datetime.utcnow().replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    coins_result = await db.execute(
        select(CoinLedger).where(
            CoinLedger.user_id == user_id,
            CoinLedger.activity_type == "MONTHLY_REPORT_UPLOAD",
            CoinLedger.created_at >= month_start,
        )
    )
    already_awarded = coins_result.scalar_one_or_none() is not None

    eligible = days_since >= 30 and not already_awarded

    return {
        "eligible": eligible,
        "days_since_last": days_since,
        "already_awarded_this_month": already_awarded,
        "last_report_date": str(last_report.uploaded_at.date()),
        "next_eligible_date": str((last_report.uploaded_at + timedelta(days=30)).date()),
        "message": (
            "Upload a new report to earn 50 coins!" if eligible
            else f"Next report due in {max(0, 30 - days_since)} days"
            if not already_awarded else "Monthly report coins already earned this month."
        ),
        "coins_reward": 50,
    }


@router.post("/step-goal")
async def update_step_goal(
    data: dict,
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Update user's daily step goal (6000–60000)."""
    goal = int(data.get("step_goal", 6000))
    goal = max(6000, min(60000, goal))

    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    user.step_goal = goal
    await db.commit()
    return {"step_goal": goal, "message": f"Step goal updated to {goal:,}"}
