from datetime import date, datetime
from typing import List
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc, func

from database import get_db
from models.domain import DailyTask, CoinLedger, User
from security.jwt_handler import get_current_user_id

router = APIRouter(prefix="/api/tasks", tags=["Tasks"])

@router.get("/today")
async def get_today_tasks(
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Get today's tasks generated by the analysis engine."""
    today = date.today()
    result = await db.execute(
        select(DailyTask)
        .where(DailyTask.user_id == user_id, DailyTask.task_date == today)
        .order_by(DailyTask.time_of_day)
    )
    tasks = result.scalars().all()
    
    # Serialize to dicts for JSON response
    return [
        {
            "id": str(t.id),
            "task_type": t.task_type,
            "task_name": t.task_name,
            "description": t.description,
            "why_this_task": t.why_this_task,
            "category": t.category,
            "time_of_day": t.time_of_day,
            "time_slot": t.time_of_day,  # Alias for Missions screen
            "duration_or_quantity": t.duration_or_quantity,
            "coins_reward": t.coins_reward,
            "completed": t.completed,
            "completed_at": str(t.completed_at) if t.completed_at else None,
        }
        for t in tasks
    ]

@router.post("/{task_id}/complete")
async def complete_task(
    task_id: str,
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Mark task as complete and award coins."""
    result = await db.execute(
        select(DailyTask).where(DailyTask.id == task_id, DailyTask.user_id == user_id)
    )
    task = result.scalar_one_or_none()
    
    if not task:
        raise HTTPException(status_code=404, detail="Task not found.")
    if task.completed:
        return {"message": "Task already completed", "coins_awarded": 0}

    # 1. Mark Complete
    task.completed = True
    task.completed_at = datetime.utcnow()

    # 2. Award Coins
    reward = CoinLedger(
        user_id=user_id,
        amount=task.coins_reward,
        activity_type=f"TASK_COMPLETION_{task.task_type}"
    )
    db.add(reward)
    
    await db.flush()
    
    # 3. Get new balance
    balance_res = await db.execute(
        select(func.sum(CoinLedger.amount)).where(CoinLedger.user_id == user_id)
    )
    new_balance = balance_res.scalar() or 0
    await db.commit()

    return {
        "message": "Task completed successfully",
        "coins_awarded": task.coins_reward,
        "new_balance": new_balance
    }

@router.get("/history")
async def get_task_history(
    limit: int = Query(50, ge=1, le=100),
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Get history of completed tasks."""
    result = await db.execute(
        select(DailyTask)
        .where(DailyTask.user_id == user_id, DailyTask.completed == True)
        .order_by(desc(DailyTask.completed_at))
        .limit(limit)
    )
    return result.scalars().all()

@router.get("/balance")
async def get_coin_balance(
    user_id: str = Depends(get_current_user_id),
    db: AsyncSession = Depends(get_db),
):
    """Calculate current coin balance."""
    result = await db.execute(
        select(func.sum(CoinLedger.amount)).where(CoinLedger.user_id == user_id)
    )
    balance = result.scalar() or 0
    return {"balance": balance}
